
export const supabaseUrl = 'https://gpaigfioahcpzixczdjj.supabase.co'; // Replace with your URL
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWlnZmlvYWhjcHppeGN6ZGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzA3MjMsImV4cCI6MjA2NDg0NjcyM30.Tb9QRetXx4CLkoH9xZylovvDuzIphKl8_xKnO2tCFTg'; 
